#164005396 login ui page
andela/LIT-Kigali1 pull request #24
Opened 2019-02-25 17:08 UTC by Nziranziza

#### What does this PR do?
Add login page UI design
#### Description of Task to be completed?
- add html
- add css
- add responsive
#### How should this be manually tested?
- git clone the branch
- npm install
- npm run build-scss
- open ./ui/pages/auth.html
#### Any background context you want to provide?
- [Desktop version Mockups](https://drive.google.com/drive/folders/1lcFZ3-tOAoN8g5_e6ORaKs8jEVI783jg)
- [Mobile version mockup](https://drive.google.com/drive/folders/1chupPda0Ny-iePagVr0_QCZgEhBabhM_)
#### What are the relevant pivotal tracker stories?
#164005396
#### Screenshots (if appropriate)
###### Desktop version
<img width="1440" alt="screen shot 2019-02-25 at 19 05 15" src="https://user-images.githubusercontent.com/37615728/53354892-7c694d00-3930-11e9-8971-57d95358140c.png">

###### Mobile version
<img width="402" alt="screen shot 2019-02-25 at 19 05 56" src="https://user-images.githubusercontent.com/37615728/53354925-960a9480-3930-11e9-98fe-73b5fcf03ccf.png">

#### Questions:

2019-02-25 18:34 UTC, oesukam requested changes
@Nziranziza Try to make the space before and after social logos to be the same

2019-02-25 18:41 UTC, oesukam requested changes
@Nziranziza There is only one main change that you can do that is to remove javascript as we are doing using html and css

2019-02-25 18:41 UTC, oesukam commented on ui/pages/auth.html
> +							<span>Already a member?</span><a onclick="flip()" href="#">Sign In</a>
@Nziranziza We are not supposed to use javascript for the mockup, just stick to html and css

2019-02-25 18:41 UTC, oesukam commented on ui/css/style.css
> +  max-width: 100vw !important; }
@Nziranziza Try to avoid using !important

2019-02-26 08:33 UTC, kimotho-njoki commented on ui/pages/auth.html
> +			function flip(){
what happened to ES6?

2019-02-26 08:33 UTC, kimotho-njoki commented on ui/pages/auth.html
> +				console.log('hello')
Why are we console logging?

2019-02-26 09:01 UTC, Nziranziza commented on ui/pages/auth.html
> +				console.log('hello')
It was for debugging I had removed it

2019-02-26 12:26 UTC, oesukam approved these changes
@Nziranziza Great work.

2019-02-26 16:37 UTC, NkFab approved these changes
Good work @Nziranziza

2019-02-27 09:04 UTC, Nziranziza commented on ui/pages/auth.html
> +			function flip(){
What do u mean???

2019-02-27 12:29 UTC, kimotho-njoki commented on ui/pages/auth.html
> +			function flip(){
I meant why can't this function be written in ES6 format?

2019-02-27 12:46 UTC, merged