#163519149 Implement email and in-app notification feature
andela/LIT-Kigali1 pull request #42
Opened 2019-03-14 16:12 UTC by mcaleb808

#### What does this PR do?
- Implement email and in-app notification feature

#### Description of Task to be completed?
- write unit tests
- create notification's model and migration
- implement notification for new article from people you follow
- implement notification for new interaction on article you liked or commented on
- implement new follower notification
- implement notification endpoints
- implement disable and enable notification option

#### How should this be manually tested?
On this branch
- Run `npm run migrate:seed`

- Run `npm run test`

- Run `npm run dev`

With postman send post requests to these endpoints:
- All notifications `GET: api/v1/notications`

- One notification `GET: api/v1/notification/:notificationId`

- Mark all notifications as read `PUT: api/v1/notification/markasread`

- Enable notification `PUT: api/v1/notification/enable`

- disable notification `PUT: api/v1/notification/disable`

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
#163519149

#### Screenshots (if appropriate)
N/A

#### Questions:
N/A

[finishes #163519149]

2019-03-15 05:37 UTC, oesukam requested changes
@mcaleb808 
Try to add more tests for coveralls

2019-03-18 10:07 UTC, NkFab approved these changes
Good work Caleb.

2019-03-18 10:12 UTC, mcaleb808 commented
> Good work Caleb.

Thank you @NkFab

2019-03-19 05:35 UTC, oesukam approved these changes

2019-03-19 06:19 UTC, oesukam commented on __tests__/routes/article.test.js
> +import { User, Article, Favorite, Report, Favorite } from '../../database/models';
@mcaleb808 You have imported the Favorite model two times

2019-03-19 07:15 UTC, mcaleb808 commented on __tests__/routes/article.test.js
> +import { User, Article, Favorite, Report, Favorite } from '../../database/models';
@oesukam I fixed that

2019-03-19 08:14 UTC, merged