#164800406 show reading stats
andela/LIT-Kigali1 pull request #49
Opened 2019-03-21 14:11 UTC by NkFab

#### What does this PR do?

Show reading stats to the user.

#### Description of Task to be completed?

- Have access to personal profile
- Show read stats 
- Show edit profile button

#### How should this be manually tested?

Clone the Repo and navigate to the UI/pages path and double click on the profile-view-stats.html

#### What are the relevant pivotal tracker stories?

#164800406

#### Screenshots (if appropriate)

![image](https://user-images.githubusercontent.com/22955494/54757932-e3a6b400-4bf3-11e9-9a2d-6fa5464b870d.png)

2019-03-21 14:47 UTC, mcaleb808 reviewed
@NkFab Please add screenshots for mobile view too!

2019-03-25 12:50 UTC, oesukam requested changes
@NkFab you need to ignore the `ui/css/style.css` file it is been compiled locally for everyone in the team.
I did not see anything to scss files or you did not need any?

2019-03-25 12:50 UTC, oesukam commented on ui/pages/profile-view-stats.html
> +</html>
@NkFab According to our code standard that we agreed on, an empty line is required at the and of every file.

2019-03-26 09:24 UTC, oesukam approved these changes

2019-03-26 09:25 UTC, mcaleb808 approved these changes

2019-03-26 09:30 UTC, filschristian approved these changes

2019-03-26 11:06 UTC, merged