#164797351 Adding more features on view article page
andela/LIT-Kigali1 pull request #50
Opened 2019-03-21 19:43 UTC by mcaleb808

#### What does this PR do?

Add more features on view article page

#### Description of Task to be completed?

- add bookmark Icons
- add social share buttons
- add five-star rating
- view ratings

#### How should this be manually tested?
On this branch 
- Clone the Repo
- Run `npm run scss`
- navigate to the UI/pages path and double click on the article-view.html

#### What are the relevant pivotal tracker stories?

#164797351

#### Screenshots (if appropriate)

![image](https://user-images.githubusercontent.com/29614532/54780298-0d76cf80-4c22-11e9-8f3a-6ee0c1dffd68.png)

![image](https://user-images.githubusercontent.com/29614532/54780355-2f705200-4c22-11e9-9b71-383f0eddbc4b.png)

#### Questions:
N/A

2019-03-25 12:21 UTC, Nziranziza approved these changes
I suggest you describe your screenshot in description section cause they are a bit confusing. For example show that one is a mobile view and another is desktop

2019-03-26 09:23 UTC, oesukam requested changes

2019-03-26 09:23 UTC, oesukam commented on ui/css/style.css
> +.rate:not(:checked) > label:hover,
@mcaleb808 Try to use nested sass feature effectively to have more specific selectors

2019-03-26 09:59 UTC, oesukam approved these changes

2019-03-26 11:44 UTC, merged