#164800557 Create tags for an article
andela/LIT-Kigali1 pull request #53
Opened 2019-03-22 15:26 UTC by NkFab

#### What does this PR do?

Add specific tags to articles

#### Description of Task to be completed?

Add tags to article ready to be published or drafted
Show tags when reading an article

#### How should this be manually tested?

Clone the Repo and navigate to the UI/pages path and double click on the articles-view.html and articles-create.html pages

What are the relevant pivotal tracker stories?
#164800557

Screenshots (if appropriate)

![image](https://user-images.githubusercontent.com/22955494/54832702-5764c180-4cc5-11e9-96df-12ac885e7cdd.png)

![image](https://user-images.githubusercontent.com/22955494/54833740-5d5ba200-4cc7-11e9-9e0c-2dde804e8a17.png)

![image](https://user-images.githubusercontent.com/22955494/54833845-8a0fb980-4cc7-11e9-8339-74ac128a98b7.png)

![image](https://user-images.githubusercontent.com/22955494/54832755-75322680-4cc5-11e9-93f7-7e10b61ad541.png)

2019-03-25 12:47 UTC, Nziranziza approved these changes
Good work @NkFab

2019-03-26 09:30 UTC, oesukam requested changes

2019-03-26 09:30 UTC, oesukam commented on ui/scss/_articles-create-page.scss
> +#tags > span {
@NkFab Try to use nested sass feature to have more specific selectors

2019-03-26 11:37 UTC, oesukam approved these changes

2019-03-26 14:18 UTC, merged